# Não é necessário ter um arquivo de Replica Set
# As specs já estão declaradas no meudeployment.yaml!

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: site
          image: kubedevio/nginx-color:green
          ports:
            - containerPort: 80
