apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      # Como cada Pod é um container, é preciso especificar
      # a porta para fazer o "bind" da porta do container
      # com a porta da minha máquina local
      nodePort: 30000
  type: NodePort
